upload first homework
webml/skypro-cardMemoryGame pull request #1
Opened 2022-08-10 19:54 UTC by webml

2022-08-11 10:40 UTC, mrerberg requested changes

2022-08-11 10:40 UTC, mrerberg commented on src/css/style.scss
> +@font-face {
Почему объявление шрифта в самом конце файла?

2022-08-11 11:03 UTC, webml commented on src/css/style.scss
> +@font-face {
На stackoverflow прочитал, что правильно подключать шрифты в конце css файла

2022-08-11 11:05 UTC, webml commented on src/css/style.scss
> +@font-face {
Я так понимаю это не правильно?

2022-08-12 06:43 UTC, mrerberg commented on src/css/style.scss
> +@font-face {
Можно, но не понимаю зачем. Это один из самых главных/начальных стилей, подключение которого ожидается в самом начале

2022-08-12 11:49 UTC, webml commented
Вынес добавление шрифта наверх файлов стилей

2022-08-13 17:25 UTC, merged